### ISSUE TITLE
[Feature]: Listen for push notifications on iOS in the Javascript layer

### ISSUE THREAD

**Issue by henrymoulton** [braze-inc/braze-react-native-sdk#174]
Hello the [documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/push_notifications/) says to use `Braze.addListener(Braze.Events.PUSH_NOTIFICATION_EVENT,` for Android, is there anyway to listen for iOS push notifications in the foreground?

Step 2.1: Listen for push notifications on Android (optional)

```
Braze.addListener(Braze.Events.PUSH_NOTIFICATION_EVENT, function(data) {
  console.log(`Push Notification event of type ${data.push_event_type} seen.
    Title ${data.title}\n and deeplink ${data.deeplink}`);
  console.log(JSON.stringify(data, undefined, 2));
});
```

We've tried to use Firebase Messaging's `.onMessage` as a workaround however we believe that Braze's setup might be blocking Firebase's `.onMessage`.

https://rnfirebase.io/messaging/usage#foreground-state-messages

**Comment by wesleyorbin** [comment]
Hi @henrymoulton. As of right now, there is no similar way to listen for iOS push notifications in the Javascript layer. I've filed a ticket internally to look into this.

**Comment by henrymoulton** [comment]
@wesleyorbin thanks for the reply.

> there is no similar way to listen for iOS push notifications in the Javascript layer

Is there any reason for this? And also do you know if a Braze PN setup would block Firebase's Messaging?

**Comment by Bucimis** [comment]
@henrymoulton iOS does not provide lifecycle events for push received or deleted, just opened. In the future, we will release an update to our Javascript APIs that will allow listening for React Native-side opened events on iOS - that work still needs to be defined and prioritized.

Braze push will not interfere with or block Firebase push from working. Braze will only process push notification payloads sent from Braze (though note that on Android, Braze uses FCM under the hood to deliver messages).

**Comment by henrymoulton** [comment]
Thanks @Bucimis, I noticed https://notifee.app/react-native/docs/ios/interaction https://notifee.app/react-native/docs/ios/remote-notification-support might be helpful documentation

```
  // Subscribe to events
  useEffect(() => {
    return notifee.onForegroundEvent(({ type, detail }) => {
      console.log('Remote notification info: ', detail.notification?.remote)
      switch (type) {
        case EventType.DISMISSED:
          console.log('User dismissed notification', detail.notification);
          break;
        case EventType.PRESS:
          console.log('User pressed notification', detail.notification);
          break;
      }
    });
```

**Comment by dgreasi** [comment]
Except of not being able to listen for push notifications on iOS when in foreground state, in our case the notification is not shown/received also. Is this the expected behaviour?

If it is similar with firebase, it's probably expected.

For firebase the solution is to trigger a local notification when an event is going to trigger the `onMessage()` handler. This is working correctly when sending notifications from Firebase to iOS devices when the app is in the foreground. Unfortunately, the `onMessage` subscription is not being triggered for notifications from Braze when the iOS app is in foreground.

Any progress on the feature or a workaround?

**Comment by ethan-park-is** [comment]
We used expo-notifications for push notification and are trying to migrate to braze. So we also tried `expo-notifications` [addnotificationreceivedlistenerlistener API](https://docs.expo.dev/versions/latest/sdk/notifications/#addnotificationreceivedlistenerlistener) as a workaround but failed.

1. without braze sdk installed, the API worked as expected. So I can assume that braze sdk blocks something
2. there is background notification event hander in `expo-notifications' which works fine with or without braze sdk installed

We want ios event listener feature so that we can handle ios app count badge and other things

**Comment by mcalc001** [comment]
> Hi @henrymoulton. As of right now, there is no similar way to listen for iOS push notifications in the Javascript layer. I've filed a ticket internally to look into this.

Hey @wesleyorbin, are there any update on the progress on this ticket? We are looking to integrate silent push notifications into our IOS app. Thanks

**Comment by jerielng** [comment]
Hey @mcalc001, our team is currently working on support for the iOS push open event as described above, and barring any unexpected obstacles, we hope to have this feature out within the next month or two.

**Comment by bheftyes** [comment]
@jerielng Is this a feature that will be added to Android too or is available now? We would like to know when the push notification is pressed on both platforms in the JavaScript layer as we use the payload to navigate the customer to that specific path (assuming the deep link has a web URL format).

**Comment by jerielng** [comment]
Hi @bheftyes, the Android push notification event is available already. You can refer to the Braze documentation [here](https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/push_notifications/?tab=expo#step-21-listen-for-push-notifications-on-android-optional).

**Comment by chrispaynter** [comment]
Hi @jerielng, @mcalc001 and I are working on a fairly high profile release with a mutual client of ours. I was wondering if there's a point of contact from your engineering team I could have a chat with in order to see if there is any possibility at all we could prioritise this? Even if it's just to explore possibility, no commitment?

**Comment by hokstuff** [comment]
Hi @chrispaynter,

Just updating this thread here. We are currently actively developing this feature on the React Native SDK, and it is currently in the verification phase before being merged into our private repo. We have prioritized this to be in the next release, which should happen in the order of weeks. We'll keep you updated when it is released - thank you for your patience!

**Comment by jerielng** [comment]
Hi all, we've just released version [8.1.0](https://github.com/braze-inc/braze-react-native-sdk/releases/tag/8.1.0) of the React Native SDK. This includes push opened events on iOS, which should now allow you to subscribe to events on both platforms where Braze has detected and handled an incoming push. Feel free to open a new thread if you have any further questions/issues.

Thank you!

**Comment by mcalc001** [comment]
> Hi all, we've just released version [8.1.0](https://github.com/braze-inc/braze-react-native-sdk/releases/tag/8.1.0) of the React Native SDK. This includes push opened events on iOS, which should now allow you to subscribe to events on both platforms where Braze has detected and handled an incoming push. Feel free to open a new thread if you have any further questions/issues.
> 
> Thank you!

Hey! Just to clarify this update enables us to detect "push_opened" events. But this doesn't seem to enable us to detect silent push notifications? We were hoping for a way to handle background notifications such as "setBackgroundMessageHandler" functionality in @react-native-firebase  https://rnfirebase.io/messaging/usage#background-application-state. Maybe i'm missing something is this possible using the Braze SDK? Thanks!

**Comment by admirsaheta** [comment]
Is there any update on this,  I am still not able to access background notifications
